/**
 * Built-in exercise library. Muscle mapping follows common hypertrophy practice: `primary` muscles
 * get a full set of volume credit, `secondary` muscles half (see volume.ts).
 */
import type { Equipment, ExerciseDef, Muscle } from '@/db/types';

type Row = [id: string, name: string, nameNl: string, equipment: Equipment, primary: Muscle[], secondary: Muscle[], kind?: ExerciseDef['kind'], met?: number];

const ROWS: Row[] = [
  // Chest
  ['bench-press', 'Bench press', 'Bankdrukken', 'barbell', ['chest'], ['frontDelts', 'triceps']],
  ['incline-bench-press', 'Incline bench press', 'Schuin bankdrukken', 'barbell', ['chest', 'frontDelts'], ['triceps']],
  ['decline-bench-press', 'Decline bench press', 'Declined bankdrukken', 'barbell', ['chest'], ['triceps']],
  ['close-grip-bench', 'Close-grip bench press', 'Smal bankdrukken', 'barbell', ['triceps', 'chest'], ['frontDelts']],
  ['db-bench-press', 'Dumbbell bench press', 'Dumbbell bankdrukken', 'dumbbell', ['chest'], ['frontDelts', 'triceps']],
  ['db-incline-press', 'Incline dumbbell press', 'Schuin dumbbell drukken', 'dumbbell', ['chest', 'frontDelts'], ['triceps']],
  ['db-fly', 'Dumbbell fly', 'Dumbbell flyes', 'dumbbell', ['chest'], ['frontDelts']],
  ['cable-fly', 'Cable fly', 'Kabel flyes', 'cable', ['chest'], ['frontDelts']],
  ['pec-deck', 'Pec deck', 'Butterfly machine', 'machine', ['chest'], []],
  ['machine-chest-press', 'Machine chest press', 'Borstpress machine', 'machine', ['chest'], ['frontDelts', 'triceps']],
  ['push-up', 'Push-up', 'Opdrukken', 'bodyweight', ['chest'], ['frontDelts', 'triceps', 'abs'], 'bodyweight'],
  ['dip', 'Dip', 'Dips', 'bodyweight', ['chest', 'triceps'], ['frontDelts'], 'bodyweight'],
  ['smith-bench-press', 'Smith machine bench press', 'Smith machine bankdrukken', 'machine', ['chest'], ['frontDelts', 'triceps']],
  ['incline-machine-press', 'Incline machine press', 'Schuine borstpress machine', 'machine', ['chest', 'frontDelts'], ['triceps']],
  ['incline-cable-fly', 'Incline cable fly', 'Schuine kabel flyes', 'cable', ['chest'], ['frontDelts']],
  ['low-to-high-cable-fly', 'Low-to-high cable fly', 'Kabel flyes laag naar hoog', 'cable', ['chest', 'frontDelts'], []],
  ['incline-push-up', 'Incline push-up', 'Opdrukken schuin (handen hoog)', 'bodyweight', ['chest'], ['frontDelts', 'triceps'], 'bodyweight'],
  ['decline-push-up', 'Decline push-up', 'Opdrukken schuin (voeten hoog)', 'bodyweight', ['chest', 'frontDelts'], ['triceps'], 'bodyweight'],
  ['machine-dip', 'Assisted / machine dip', 'Dips machine (geassisteerd)', 'machine', ['chest', 'triceps'], ['frontDelts']],
  // Back
  ['deadlift', 'Deadlift', 'Deadlift', 'barbell', ['hamstrings', 'glutes', 'lowerBack'], ['traps', 'upperBack', 'lats', 'forearms', 'quads']],
  ['romanian-deadlift', 'Romanian deadlift', 'Roemeense deadlift', 'barbell', ['hamstrings', 'glutes'], ['lowerBack', 'forearms']],
  ['barbell-row', 'Barbell row', 'Barbell roeien', 'barbell', ['upperBack', 'lats'], ['rearDelts', 'biceps', 'lowerBack']],
  ['pendlay-row', 'Pendlay row', 'Pendlay row', 'barbell', ['upperBack', 'lats'], ['rearDelts', 'biceps', 'lowerBack']],
  ['db-row', 'One-arm dumbbell row', 'Eenarmig dumbbell roeien', 'dumbbell', ['lats', 'upperBack'], ['rearDelts', 'biceps']],
  ['seated-cable-row', 'Seated cable row', 'Kabel roeien zittend', 'cable', ['upperBack', 'lats'], ['rearDelts', 'biceps']],
  ['chest-supported-row', 'Chest-supported row', 'Borstgesteund roeien', 'machine', ['upperBack', 'lats'], ['rearDelts', 'biceps']],
  ['t-bar-row', 'T-bar row', 'T-bar roeien', 'barbell', ['upperBack', 'lats'], ['rearDelts', 'biceps', 'lowerBack']],
  ['pull-up', 'Pull-up', 'Optrekken', 'bodyweight', ['lats'], ['biceps', 'upperBack', 'forearms'], 'bodyweight'],
  ['chin-up', 'Chin-up', 'Chin-up', 'bodyweight', ['lats', 'biceps'], ['upperBack', 'forearms'], 'bodyweight'],
  ['lat-pulldown', 'Lat pulldown', 'Lat pulldown', 'cable', ['lats'], ['biceps', 'upperBack']],
  ['close-grip-pulldown', 'Close-grip pulldown', 'Smalle lat pulldown', 'cable', ['lats'], ['biceps', 'upperBack']],
  ['straight-arm-pulldown', 'Straight-arm pulldown', 'Pullover aan de kabel', 'cable', ['lats'], ['triceps']],
  ['db-pullover', 'Dumbbell pullover', 'Dumbbell pullover', 'dumbbell', ['lats', 'chest'], ['triceps']],
  ['face-pull', 'Face pull', 'Face pull', 'cable', ['rearDelts', 'upperBack'], ['traps']],
  ['barbell-shrug', 'Barbell shrug', 'Shrugs barbell', 'barbell', ['traps'], ['forearms']],
  ['db-shrug', 'Dumbbell shrug', 'Shrugs dumbbell', 'dumbbell', ['traps'], ['forearms']],
  ['back-extension', 'Back extension', 'Rugextensie', 'bodyweight', ['lowerBack', 'glutes'], ['hamstrings'], 'bodyweight'],
  ['good-morning', 'Good morning', 'Good morning', 'barbell', ['hamstrings', 'lowerBack'], ['glutes']],
  ['rack-pull', 'Rack pull', 'Rack pull', 'barbell', ['lowerBack', 'traps', 'glutes'], ['hamstrings', 'upperBack', 'forearms']],
  ['trap-bar-deadlift', 'Trap bar deadlift', 'Trap bar deadlift', 'barbell', ['quads', 'glutes', 'hamstrings'], ['lowerBack', 'traps', 'forearms']],
  ['stiff-leg-deadlift', 'Stiff-leg deadlift', 'Stiff-leg deadlift', 'barbell', ['hamstrings'], ['glutes', 'lowerBack']],
  ['db-romanian-deadlift', 'Dumbbell Romanian deadlift', 'Roemeense deadlift dumbbell', 'dumbbell', ['hamstrings', 'glutes'], ['lowerBack', 'forearms']],
  ['machine-row', 'Machine row', 'Roeimachine (kracht)', 'machine', ['upperBack', 'lats'], ['rearDelts', 'biceps']],
  ['seal-row', 'Seal row', 'Seal row', 'barbell', ['upperBack', 'lats'], ['rearDelts', 'biceps']],
  ['meadows-row', 'Meadows row', 'Meadows row', 'barbell', ['lats', 'upperBack'], ['rearDelts', 'biceps', 'forearms']],
  ['single-arm-cable-row', 'Single-arm cable row', 'Eenarmig kabel roeien', 'cable', ['lats', 'upperBack'], ['rearDelts', 'biceps']],
  ['inverted-row', 'Inverted row', 'Australian pull-up', 'bodyweight', ['upperBack', 'lats'], ['rearDelts', 'biceps'], 'bodyweight'],
  ['assisted-pull-up', 'Assisted pull-up (machine)', 'Optrekken geassisteerd', 'machine', ['lats'], ['biceps', 'upperBack']],
  ['single-arm-pulldown', 'Single-arm lat pulldown', 'Eenarmige lat pulldown', 'cable', ['lats'], ['biceps', 'upperBack']],
  ['machine-pullover', 'Machine pullover', 'Pullover machine', 'machine', ['lats'], ['chest', 'triceps']],
  ['band-pull-apart', 'Band pull-apart', 'Band pull-apart', 'band', ['rearDelts', 'upperBack'], ['traps']],
  ['reverse-hyper', 'Reverse hyperextension', 'Reverse hyperextensie', 'machine', ['glutes', 'lowerBack'], ['hamstrings']],
  // Shoulders
  ['overhead-press', 'Overhead press', 'Military press', 'barbell', ['frontDelts'], ['sideDelts', 'triceps', 'upperBack']],
  ['db-shoulder-press', 'Dumbbell shoulder press', 'Dumbbell schouderdrukken', 'dumbbell', ['frontDelts'], ['sideDelts', 'triceps']],
  ['arnold-press', 'Arnold press', 'Arnold press', 'dumbbell', ['frontDelts', 'sideDelts'], ['triceps']],
  ['machine-shoulder-press', 'Machine shoulder press', 'Schouderpress machine', 'machine', ['frontDelts'], ['sideDelts', 'triceps']],
  ['lateral-raise', 'Lateral raise', 'Zijwaartse raise', 'dumbbell', ['sideDelts'], ['traps']],
  ['cable-lateral-raise', 'Cable lateral raise', 'Kabel zijwaartse raise', 'cable', ['sideDelts'], []],
  ['machine-lateral-raise', 'Machine lateral raise', 'Zijwaartse raise machine', 'machine', ['sideDelts'], []],
  ['front-raise', 'Front raise', 'Front raise', 'dumbbell', ['frontDelts'], []],
  ['rear-delt-fly', 'Rear delt fly', 'Reverse flyes', 'dumbbell', ['rearDelts'], ['upperBack']],
  ['reverse-pec-deck', 'Reverse pec deck', 'Reverse butterfly', 'machine', ['rearDelts'], ['upperBack']],
  ['upright-row', 'Upright row', 'Upright row', 'barbell', ['sideDelts', 'traps'], ['biceps']],
  ['smith-shoulder-press', 'Smith machine shoulder press', 'Smith machine schouderdrukken', 'machine', ['frontDelts'], ['sideDelts', 'triceps']],
  ['push-press', 'Push press', 'Push press', 'barbell', ['frontDelts', 'triceps'], ['sideDelts', 'quads', 'glutes']],
  ['landmine-press', 'Landmine press', 'Landmine press', 'barbell', ['frontDelts', 'chest'], ['triceps', 'obliques']],
  ['pike-push-up', 'Pike push-up', 'Pike push-up', 'bodyweight', ['frontDelts'], ['triceps', 'sideDelts'], 'bodyweight'],
  ['cable-front-raise', 'Cable front raise', 'Kabel front raise', 'cable', ['frontDelts'], []],
  ['cable-rear-delt-fly', 'Cable rear delt fly', 'Kabel reverse flyes', 'cable', ['rearDelts'], ['upperBack']],
  ['db-upright-row', 'Dumbbell upright row', 'Upright row dumbbell', 'dumbbell', ['sideDelts', 'traps'], ['biceps']],
  ['y-raise', 'Y-raise', 'Y-raise', 'dumbbell', ['sideDelts', 'traps'], ['rearDelts']],
  // Arms
  ['barbell-curl', 'Barbell curl', 'Barbell curl', 'barbell', ['biceps'], ['forearms']],
  ['ez-bar-curl', 'EZ-bar curl', 'EZ-bar curl', 'barbell', ['biceps'], ['forearms']],
  ['db-curl', 'Dumbbell curl', 'Dumbbell curl', 'dumbbell', ['biceps'], ['forearms']],
  ['hammer-curl', 'Hammer curl', 'Hammer curl', 'dumbbell', ['biceps', 'forearms'], []],
  ['incline-db-curl', 'Incline dumbbell curl', 'Schuine dumbbell curl', 'dumbbell', ['biceps'], []],
  ['preacher-curl', 'Preacher curl', 'Preacher curl', 'machine', ['biceps'], []],
  ['cable-curl', 'Cable curl', 'Kabel curl', 'cable', ['biceps'], ['forearms']],
  ['concentration-curl', 'Concentration curl', 'Concentratie curl', 'dumbbell', ['biceps'], []],
  ['triceps-pushdown', 'Triceps pushdown', 'Triceps pushdown', 'cable', ['triceps'], []],
  ['overhead-triceps-extension', 'Overhead triceps extension', 'Triceps extensie boven hoofd', 'cable', ['triceps'], []],
  ['skull-crusher', 'Skull crusher', 'Skull crusher', 'barbell', ['triceps'], []],
  ['db-kickback', 'Dumbbell kickback', 'Triceps kickback', 'dumbbell', ['triceps'], []],
  ['bench-dip', 'Bench dip', 'Bankdips', 'bodyweight', ['triceps'], ['chest', 'frontDelts'], 'bodyweight'],
  ['wrist-curl', 'Wrist curl', 'Polscurl', 'dumbbell', ['forearms'], []],
  ['reverse-curl', 'Reverse curl', 'Reverse curl', 'barbell', ['forearms', 'biceps'], []],
  ['farmers-walk', "Farmer's walk", 'Farmer walk', 'dumbbell', ['forearms', 'traps'], ['abs', 'glutes']],
  ['spider-curl', 'Spider curl', 'Spider curl', 'dumbbell', ['biceps'], []],
  ['bayesian-curl', 'Bayesian cable curl', 'Bayesian kabel curl', 'cable', ['biceps'], []],
  ['machine-curl', 'Machine curl', 'Bicepsmachine', 'machine', ['biceps'], []],
  ['db-preacher-curl', 'Dumbbell preacher curl', 'Preacher curl dumbbell', 'dumbbell', ['biceps'], []],
  ['rope-hammer-curl', 'Rope hammer curl', 'Hammer curl aan de kabel', 'cable', ['biceps', 'forearms'], []],
  ['rope-pushdown', 'Rope pushdown', 'Triceps pushdown touw', 'cable', ['triceps'], []],
  ['single-arm-pushdown', 'Single-arm pushdown', 'Eenarmige triceps pushdown', 'cable', ['triceps'], []],
  ['db-overhead-extension', 'Dumbbell overhead triceps extension', 'Triceps extensie dumbbell boven hoofd', 'dumbbell', ['triceps'], []],
  ['jm-press', 'JM press', 'JM press', 'barbell', ['triceps'], ['chest']],
  ['triceps-dip-machine', 'Triceps dip machine', 'Triceps dipmachine', 'machine', ['triceps'], ['chest']],
  ['diamond-push-up', 'Diamond push-up', 'Diamant opdrukken', 'bodyweight', ['triceps', 'chest'], ['frontDelts'], 'bodyweight'],
  ['reverse-wrist-curl', 'Reverse wrist curl', 'Omgekeerde polscurl', 'dumbbell', ['forearms'], []],
  ['dead-hang', 'Dead hang', 'Hangen aan de stang', 'bodyweight', ['forearms'], ['lats'], 'bodyweight'],
  // Legs
  ['back-squat', 'Back squat', 'Squat', 'barbell', ['quads', 'glutes'], ['adductors', 'lowerBack', 'hamstrings']],
  ['front-squat', 'Front squat', 'Front squat', 'barbell', ['quads'], ['glutes', 'abs', 'upperBack']],
  ['goblet-squat', 'Goblet squat', 'Goblet squat', 'dumbbell', ['quads', 'glutes'], ['adductors', 'abs']],
  ['hack-squat', 'Hack squat', 'Hack squat', 'machine', ['quads'], ['glutes']],
  ['leg-press', 'Leg press', 'Beenpers', 'machine', ['quads', 'glutes'], ['adductors', 'hamstrings']],
  ['bulgarian-split-squat', 'Bulgarian split squat', 'Bulgaarse split squat', 'dumbbell', ['quads', 'glutes'], ['adductors', 'hamstrings']],
  ['walking-lunge', 'Walking lunge', 'Lunges lopend', 'dumbbell', ['quads', 'glutes'], ['hamstrings', 'adductors']],
  ['step-up', 'Step-up', 'Step-up', 'dumbbell', ['quads', 'glutes'], ['hamstrings']],
  ['leg-extension', 'Leg extension', 'Beenstrekken', 'machine', ['quads'], []],
  ['lying-leg-curl', 'Lying leg curl', 'Liggende leg curl', 'machine', ['hamstrings'], ['calves']],
  ['seated-leg-curl', 'Seated leg curl', 'Zittende leg curl', 'machine', ['hamstrings'], []],
  ['nordic-curl', 'Nordic curl', 'Nordic curl', 'bodyweight', ['hamstrings'], ['glutes'], 'bodyweight'],
  ['hip-thrust', 'Hip thrust', 'Hip thrust', 'barbell', ['glutes'], ['hamstrings', 'quads']],
  ['glute-bridge', 'Glute bridge', 'Glute bridge', 'bodyweight', ['glutes'], ['hamstrings'], 'bodyweight'],
  ['cable-kickback', 'Cable glute kickback', 'Kabel kickback', 'cable', ['glutes'], ['hamstrings']],
  ['hip-abduction', 'Hip abduction', 'Abductor machine', 'machine', ['glutes'], []],
  ['hip-adduction', 'Hip adduction', 'Adductor machine', 'machine', ['adductors'], []],
  ['sumo-deadlift', 'Sumo deadlift', 'Sumo deadlift', 'barbell', ['glutes', 'quads', 'adductors'], ['hamstrings', 'lowerBack', 'traps', 'forearms']],
  ['kettlebell-swing', 'Kettlebell swing', 'Kettlebell swing', 'kettlebell', ['glutes', 'hamstrings'], ['lowerBack', 'abs', 'forearms']],
  ['standing-calf-raise', 'Standing calf raise', 'Kuitheffen staand', 'machine', ['calves'], []],
  ['seated-calf-raise', 'Seated calf raise', 'Kuitheffen zittend', 'machine', ['calves'], []],
  ['leg-press-calf-raise', 'Leg press calf raise', 'Kuitheffen beenpers', 'machine', ['calves'], []],
  ['smith-squat', 'Smith machine squat', 'Smith machine squat', 'machine', ['quads', 'glutes'], ['adductors']],
  ['pendulum-squat', 'Pendulum squat', 'Pendulum squat', 'machine', ['quads'], ['glutes']],
  ['belt-squat', 'Belt squat', 'Belt squat', 'machine', ['quads', 'glutes'], ['adductors']],
  ['box-squat', 'Box squat', 'Box squat', 'barbell', ['quads', 'glutes'], ['hamstrings', 'adductors', 'lowerBack']],
  ['bodyweight-squat', 'Bodyweight squat', 'Squat zonder gewicht', 'bodyweight', ['quads', 'glutes'], ['adductors'], 'bodyweight'],
  ['jump-squat', 'Jump squat', 'Squat jump', 'bodyweight', ['quads', 'glutes'], ['calves'], 'bodyweight', 8],
  ['box-jump', 'Box jump', 'Box jump', 'bodyweight', ['quads', 'glutes'], ['calves', 'hamstrings'], 'bodyweight', 8],
  ['split-squat', 'Split squat', 'Split squat', 'dumbbell', ['quads', 'glutes'], ['adductors', 'hamstrings']],
  ['reverse-lunge', 'Reverse lunge', 'Achterwaartse lunge', 'dumbbell', ['quads', 'glutes'], ['hamstrings', 'adductors']],
  ['barbell-lunge', 'Barbell lunge', 'Lunges met barbell', 'barbell', ['quads', 'glutes'], ['hamstrings', 'adductors']],
  ['cossack-squat', 'Cossack squat', 'Cossack squat', 'bodyweight', ['adductors', 'quads'], ['glutes'], 'bodyweight'],
  ['pistol-squat', 'Pistol squat', 'Pistol squat', 'bodyweight', ['quads', 'glutes'], ['adductors', 'calves'], 'bodyweight'],
  ['sissy-squat', 'Sissy squat', 'Sissy squat', 'bodyweight', ['quads'], [], 'bodyweight'],
  ['wall-sit', 'Wall sit', 'Muurzit', 'bodyweight', ['quads'], ['glutes'], 'bodyweight'],
  ['single-leg-rdl', 'Single-leg Romanian deadlift', 'Eenbenige Roemeense deadlift', 'dumbbell', ['hamstrings', 'glutes'], ['lowerBack']],
  ['glute-ham-raise', 'Glute-ham raise', 'Glute-ham raise', 'bodyweight', ['hamstrings'], ['glutes', 'calves'], 'bodyweight'],
  ['standing-leg-curl', 'Standing leg curl', 'Staande leg curl', 'machine', ['hamstrings'], []],
  ['single-leg-hip-thrust', 'Single-leg hip thrust', 'Eenbenige hip thrust', 'bodyweight', ['glutes'], ['hamstrings'], 'bodyweight'],
  ['machine-hip-thrust', 'Machine hip thrust', 'Hip thrust machine', 'machine', ['glutes'], ['hamstrings']],
  ['cable-pull-through', 'Cable pull-through', 'Kabel pull-through', 'cable', ['glutes', 'hamstrings'], ['lowerBack']],
  ['db-calf-raise', 'Dumbbell calf raise', 'Kuitheffen dumbbell', 'dumbbell', ['calves'], []],
  ['single-leg-calf-raise', 'Single-leg calf raise', 'Eenbenig kuitheffen', 'bodyweight', ['calves'], [], 'bodyweight'],
  ['sled-push', 'Sled push', 'Slee duwen', 'other', ['quads', 'glutes'], ['calves', 'frontDelts', 'triceps']],
  // Core
  ['plank', 'Plank', 'Plank', 'bodyweight', ['abs'], ['obliques'], 'bodyweight'],
  ['side-plank', 'Side plank', 'Zijplank', 'bodyweight', ['obliques'], ['abs'], 'bodyweight'],
  ['crunch', 'Crunch', 'Crunch', 'bodyweight', ['abs'], [], 'bodyweight'],
  ['cable-crunch', 'Cable crunch', 'Kabel crunch', 'cable', ['abs'], ['obliques']],
  ['hanging-leg-raise', 'Hanging leg raise', 'Hangend beenheffen', 'bodyweight', ['abs'], ['obliques', 'forearms'], 'bodyweight'],
  ['ab-wheel', 'Ab wheel rollout', 'Ab wheel', 'other', ['abs'], ['lats', 'obliques']],
  ['russian-twist', 'Russian twist', 'Russian twist', 'bodyweight', ['obliques'], ['abs'], 'bodyweight'],
  ['pallof-press', 'Pallof press', 'Pallof press', 'cable', ['obliques', 'abs'], []],
  ['dead-bug', 'Dead bug', 'Dead bug', 'bodyweight', ['abs'], [], 'bodyweight'],
  ['sit-up', 'Sit-up', 'Sit-up', 'bodyweight', ['abs'], ['obliques'], 'bodyweight'],
  ['decline-sit-up', 'Decline sit-up', 'Sit-up op schuine bank', 'bodyweight', ['abs'], ['obliques'], 'bodyweight'],
  ['reverse-crunch', 'Reverse crunch', 'Reverse crunch', 'bodyweight', ['abs'], ['obliques'], 'bodyweight'],
  ['bicycle-crunch', 'Bicycle crunch', 'Fietscrunch', 'bodyweight', ['obliques', 'abs'], [], 'bodyweight'],
  ['lying-leg-raise', 'Lying leg raise', 'Liggend beenheffen', 'bodyweight', ['abs'], ['obliques'], 'bodyweight'],
  ['hanging-knee-raise', 'Hanging knee raise', 'Hangend knieheffen', 'bodyweight', ['abs'], ['obliques', 'forearms'], 'bodyweight'],
  ['captains-chair-raise', "Captain's chair knee raise", 'Knieheffen in de dipstation', 'bodyweight', ['abs'], ['obliques'], 'bodyweight'],
  ['toes-to-bar', 'Toes to bar', 'Toes to bar', 'bodyweight', ['abs'], ['obliques', 'lats', 'forearms'], 'bodyweight'],
  ['v-up', 'V-up', 'V-up', 'bodyweight', ['abs'], ['obliques'], 'bodyweight'],
  ['hollow-hold', 'Hollow body hold', 'Hollow hold', 'bodyweight', ['abs'], [], 'bodyweight'],
  ['flutter-kicks', 'Flutter kicks', 'Flutter kicks', 'bodyweight', ['abs'], [], 'bodyweight'],
  ['mountain-climber', 'Mountain climber', 'Mountain climbers', 'bodyweight', ['abs'], ['frontDelts', 'quads'], 'bodyweight', 8],
  ['heel-touch', 'Heel touches', 'Hielaantikken', 'bodyweight', ['obliques'], ['abs'], 'bodyweight'],
  ['ab-crunch-machine', 'Ab crunch machine', 'Buikspiermachine', 'machine', ['abs'], []],
  ['weighted-crunch', 'Weighted crunch', 'Crunch met gewicht', 'dumbbell', ['abs'], []],
  ['cable-woodchopper', 'Cable woodchopper', 'Houthakker aan de kabel', 'cable', ['obliques'], ['abs']],
  ['db-side-bend', 'Dumbbell side bend', 'Zijwaarts buigen dumbbell', 'dumbbell', ['obliques'], []],
  ['oblique-crunch', 'Oblique crunch', 'Schuine crunch', 'bodyweight', ['obliques'], ['abs'], 'bodyweight'],
  ['landmine-rotation', 'Landmine rotation', 'Landmine rotatie', 'barbell', ['obliques'], ['abs', 'frontDelts']],
  ['stir-the-pot', 'Stir the pot', 'Stir the pot', 'other', ['abs'], ['obliques'], 'bodyweight'],
  ['bird-dog', 'Bird dog', 'Bird dog', 'bodyweight', ['lowerBack', 'abs'], ['glutes'], 'bodyweight'],
  ['superman', 'Superman', 'Superman', 'bodyweight', ['lowerBack'], ['glutes'], 'bodyweight'],
  // Full body / Olympic
  ['power-clean', 'Power clean', 'Power clean', 'barbell', ['glutes', 'hamstrings', 'traps'], ['quads', 'upperBack', 'lowerBack', 'forearms']],
  ['thruster', 'Thruster', 'Thruster', 'barbell', ['quads', 'frontDelts'], ['glutes', 'triceps']],
  ['burpee', 'Burpee', 'Burpee', 'bodyweight', ['quads', 'chest'], ['frontDelts', 'triceps', 'abs'], 'bodyweight', 8],
  ['clean-and-jerk', 'Clean and jerk', 'Clean and jerk', 'barbell', ['quads', 'glutes', 'frontDelts'], ['traps', 'triceps', 'hamstrings', 'upperBack']],
  ['snatch', 'Snatch', 'Snatch', 'barbell', ['glutes', 'hamstrings', 'traps'], ['quads', 'frontDelts', 'upperBack', 'lowerBack']],
  ['kettlebell-clean-press', 'Kettlebell clean and press', 'Kettlebell clean en press', 'kettlebell', ['frontDelts', 'glutes'], ['triceps', 'hamstrings', 'abs']],
  ['turkish-get-up', 'Turkish get-up', 'Turkish get-up', 'kettlebell', ['frontDelts', 'abs'], ['obliques', 'glutes', 'triceps']],
  ['kettlebell-goblet-squat', 'Kettlebell goblet squat', 'Goblet squat kettlebell', 'kettlebell', ['quads', 'glutes'], ['adductors', 'abs']],
  ['wall-ball', 'Wall ball', 'Wall ball', 'other', ['quads', 'frontDelts'], ['glutes', 'triceps'], 'bodyweight', 8],
  // Cardio (MET values from the Compendium of Physical Activities)
  ['running', 'Running', 'Hardlopen', 'cardio', ['quads', 'calves'], ['hamstrings', 'glutes'], 'cardio', 9.8],
  ['treadmill-walk', 'Treadmill walk (incline)', 'Lopen op loopband (helling)', 'cardio', ['calves', 'glutes'], ['hamstrings'], 'cardio', 6],
  ['walking', 'Walking', 'Wandelen', 'cardio', ['calves'], ['quads'], 'cardio', 3.5],
  ['cycling', 'Cycling', 'Fietsen', 'cardio', ['quads'], ['glutes', 'calves'], 'cardio', 7.5],
  ['stationary-bike', 'Stationary bike', 'Hometrainer', 'cardio', ['quads'], ['glutes', 'calves'], 'cardio', 6.8],
  ['rowing-machine', 'Rowing machine', 'Roeimachine', 'cardio', ['upperBack', 'quads'], ['lats', 'biceps', 'glutes'], 'cardio', 7],
  ['elliptical', 'Elliptical', 'Crosstrainer', 'cardio', ['quads', 'glutes'], ['calves'], 'cardio', 5],
  ['stair-climber', 'Stair climber', 'Traploper', 'cardio', ['glutes', 'quads'], ['calves'], 'cardio', 9],
  ['swimming', 'Swimming', 'Zwemmen', 'cardio', ['lats', 'frontDelts'], ['triceps', 'quads'], 'cardio', 7],
  ['jump-rope', 'Jump rope', 'Touwtjespringen', 'cardio', ['calves'], ['quads', 'frontDelts'], 'cardio', 11],
  ['hiit', 'HIIT / circuit class', 'HIIT / circuittraining', 'cardio', ['quads', 'glutes'], ['chest', 'abs', 'calves'], 'cardio', 8],
  ['spinning', 'Spinning class', 'Spinning', 'cardio', ['quads'], ['glutes', 'calves'], 'cardio', 8.5],
  ['hiking', 'Hiking', 'Wandeltocht', 'cardio', ['quads', 'calves'], ['glutes', 'hamstrings'], 'cardio', 6],
  ['air-bike', 'Air bike / assault bike', 'Airbike', 'cardio', ['quads'], ['glutes', 'frontDelts', 'triceps'], 'cardio', 8.5],
  ['ski-erg', 'Ski erg', 'Ski erg', 'cardio', ['lats', 'triceps'], ['abs', 'upperBack', 'quads'], 'cardio', 7.5],
  ['battle-ropes', 'Battle ropes', 'Battle ropes', 'cardio', ['frontDelts'], ['abs', 'forearms', 'sideDelts'], 'cardio', 8],
  ['nordic-walking', 'Nordic walking', 'Nordic walking', 'cardio', ['calves', 'quads'], ['lats', 'triceps'], 'cardio', 4.8],
  ['mountain-biking', 'Mountain biking', 'Mountainbiken', 'cardio', ['quads', 'glutes'], ['calves', 'forearms'], 'cardio', 8.5],
  // Sports: logged in minutes. MET values from the 2024 Compendium of Physical Activities
  // (team-game or training intensity; korfball has no entry and uses the general team-sport value).
  ['volleyball', 'Volleyball (training / match)', 'Volleybal', 'sport', ['quads', 'calves', 'frontDelts'], ['glutes', 'abs', 'sideDelts'], 'cardio', 6],
  ['beach-volleyball', 'Beach volleyball', 'Beachvolleybal', 'sport', ['quads', 'calves', 'glutes'], ['frontDelts', 'abs'], 'cardio', 8],
  ['basketball', 'Basketball (match)', 'Basketbal (wedstrijd)', 'sport', ['quads', 'calves'], ['glutes', 'hamstrings', 'frontDelts'], 'cardio', 8],
  ['basketball-training', 'Basketball (training / shooting)', 'Basketbal (training)', 'sport', ['quads', 'calves'], ['frontDelts', 'triceps'], 'cardio', 6.5],
  ['soccer', 'Football (soccer)', 'Voetbal', 'sport', ['quads', 'hamstrings', 'calves'], ['glutes', 'adductors'], 'cardio', 7],
  ['soccer-match', 'Football match (competitive)', 'Voetbalwedstrijd', 'sport', ['quads', 'hamstrings', 'calves'], ['glutes', 'adductors'], 'cardio', 10],
  ['field-hockey', 'Field hockey', 'Hockey', 'sport', ['quads', 'glutes'], ['lowerBack', 'forearms', 'calves'], 'cardio', 7.8],
  ['korfball', 'Korfball', 'Korfbal', 'sport', ['quads', 'calves'], ['frontDelts', 'glutes'], 'cardio', 7],
  ['handball', 'Handball', 'Handbal', 'sport', ['quads', 'frontDelts'], ['calves', 'glutes', 'triceps'], 'cardio', 8],
  ['rugby', 'Rugby', 'Rugby', 'sport', ['quads', 'glutes', 'hamstrings'], ['traps', 'upperBack'], 'cardio', 8.3],
  ['tennis', 'Tennis', 'Tennis', 'sport', ['quads', 'forearms'], ['frontDelts', 'obliques', 'calves'], 'cardio', 7.3],
  ['padel', 'Padel', 'Padel', 'sport', ['quads', 'forearms'], ['frontDelts', 'obliques', 'calves'], 'cardio', 6],
  ['squash', 'Squash', 'Squash', 'sport', ['quads', 'calves'], ['forearms', 'obliques'], 'cardio', 7.3],
  ['badminton', 'Badminton', 'Badminton', 'sport', ['calves', 'quads'], ['frontDelts', 'forearms'], 'cardio', 5.5],
  ['table-tennis', 'Table tennis', 'Tafeltennis', 'sport', ['forearms'], ['quads', 'obliques'], 'cardio', 4],
  ['boxing-bag', 'Boxing (bag / pads)', 'Boksen (zak / pads)', 'sport', ['frontDelts', 'triceps'], ['abs', 'obliques', 'calves'], 'cardio', 5.5],
  ['boxing-sparring', 'Boxing (sparring)', 'Boksen (sparren)', 'sport', ['frontDelts', 'triceps', 'calves'], ['abs', 'obliques'], 'cardio', 7.8],
  ['martial-arts', 'Martial arts / kickboxing', 'Vechtsport / kickboksen', 'sport', ['quads', 'frontDelts'], ['abs', 'obliques', 'glutes'], 'cardio', 10.3],
  ['climbing', 'Climbing / bouldering', 'Klimmen / boulderen', 'sport', ['lats', 'forearms'], ['biceps', 'upperBack', 'abs'], 'cardio', 5.8],
  ['yoga', 'Yoga', 'Yoga', 'sport', ['abs'], ['hamstrings', 'glutes', 'frontDelts'], 'cardio', 2.5],
  ['pilates', 'Pilates', 'Pilates', 'sport', ['abs', 'obliques'], ['glutes', 'lowerBack'], 'cardio', 3],
  ['dancing', 'Dancing', 'Dansen', 'sport', ['calves', 'quads'], ['glutes'], 'cardio', 5],
  ['ice-skating', 'Ice skating', 'Schaatsen', 'sport', ['quads', 'glutes'], ['adductors', 'calves'], 'cardio', 7],
  ['inline-skating', 'Inline skating', 'Skeeleren', 'sport', ['quads', 'glutes'], ['adductors', 'calves'], 'cardio', 7.5],
  ['skiing', 'Downhill skiing', 'Skiën', 'sport', ['quads', 'glutes'], ['calves', 'abs'], 'cardio', 5.3],
  ['cross-country-skiing', 'Cross-country skiing', 'Langlaufen', 'sport', ['quads', 'lats'], ['triceps', 'glutes', 'calves'], 'cardio', 9],
  ['golf', 'Golf (walking)', 'Golf (lopend)', 'sport', ['obliques'], ['forearms', 'glutes'], 'cardio', 4.8],
];

/** MET per equipment/kind for strength work when an exercise has none (vigorous resistance training ~5). */
const DEFAULT_MET: Record<ExerciseDef['kind'], number> = { strength: 5, bodyweight: 4.5, cardio: 6 };

export const BUILT_IN_EXERCISES: ExerciseDef[] = ROWS.map(([id, name, nameNl, equipment, primary, secondary, kind, met]) => {
  const k = kind ?? (equipment === 'bodyweight' ? 'bodyweight' : 'strength');
  return { id, name, nameNl, equipment, primary, secondary, kind: k, met: met ?? DEFAULT_MET[k] };
});

const BY_ID = new Map(BUILT_IN_EXERCISES.map((e) => [e.id, e]));

export function builtInExercise(id: string): ExerciseDef | undefined {
  return BY_ID.get(id);
}

export const MUSCLES: Muscle[] = ['chest', 'frontDelts', 'sideDelts', 'rearDelts', 'biceps', 'triceps', 'forearms', 'lats', 'upperBack', 'traps', 'lowerBack', 'abs', 'obliques', 'glutes', 'quads', 'hamstrings', 'adductors', 'calves'];

export const MUSCLE_LABEL: Record<Muscle, string> = {
  chest: 'Chest', frontDelts: 'Front delts', sideDelts: 'Side delts', rearDelts: 'Rear delts', biceps: 'Biceps', triceps: 'Triceps',
  forearms: 'Forearms', lats: 'Lats', upperBack: 'Upper back', traps: 'Traps', lowerBack: 'Lower back', abs: 'Abs', obliques: 'Obliques',
  glutes: 'Glutes', quads: 'Quads', hamstrings: 'Hamstrings', adductors: 'Adductors', calves: 'Calves',
};
